### PR TITLE
Deprecate 'data' for 'body', and respect existing query strings

### PR DESCRIPTION
**Pull request by flintinatux**
dilbert

The big issue here was `gimme` didn't support using presigned `PUT` urls from AWS S3.  It completely ignored any existing query string, and only used the `query` option if supplied.  This fixes that.

I also got tired of wondering where `data` was going to end up in the request.  It was a terrible idea when I originally made `data` go in the query for `GET` requests and in the body for others.  We eventually made it only go in the body, but I've decided it's time to be more descriptive and prefer a `body` option instead.   We'll still accept `data`, but we'll deprecate it, and issue a warning as such whenever it is used.

### CODE REVIEW

**Comment by mgreystone** [comment]
Closes https://github.com/articulate/gimme/issues/9?

**Comment by flintinatux** [comment]
@mgreystone, yes, it looks like it does.  I decided to allow both existing querystring params and a supplied `query` option, and to let the latter override the former to build the final url.

**Comment by mgreystone** [comment]
:disappointed: Nothing but red herrings. My hardware is not able to test anything atm. Code looks good to me, though.

**Comment by flintinatux** [comment]
squirrel

**Pull request merged**
